---
- name: "Install app node" 
  hosts: aula
  become: yes
  gather_facts: yes
  vars:
    file_src: "https://github.com/bgsouza/app_node2/archive/master.zip"
    path_app: "/usr/app"
    tasks:
     - name: "1 - Criar o diretório"
       file:
         path: "{{file_dest}}"
         state: directory
         mode: 0755    

     - name: "2 - Instalar a dependência unzip" 
       package:
         name: 
           - unzip
         state: present

     - name: "3 - Download e Descompactar"
       unarchive:
         src: "{{file_src}}"
         dest: "{{file_dest}}"
         remote_src: yes
       
     - name: "4 - Compilando o app"
       npm:
         name: Master
         path: "{{file_dest}}"

     - name: "5 - Gerenciador node pm2"
       npm:
         name: pm2
         global: yes

    #  - name: "6 - Rodando o app pm2 start {{path_app}}/{{app_name}}/app.js" 

